fix: use reduce-overhead compilation (#25)
max-autotune causes an error. TODO: understand this.

This causes the crash:

python \
        src/LatentEvolution/latent.py \
        --training.batch_size 128 \
        --training.epochs 5000 \
        --training.learning_rate 0.0001
Error msg:

object address  : 0x746b97643d20
object refcount : 3
object type     : 0x597e41c31840
object type name: InductorError
object repr     : InductorError("TypeError: launcher() missing 1 required positional argument: '_grid_2'")